#!/usr/bin/env python

import argparse
import pandas as pd

from moscatel.utils import df_phot, plot_matrix, plot_params, plot_multicolor, df_phot_multicolor, df_phot_multicolor2

parser = argparse.ArgumentParser(description="Do differential photometry by dividing flux of target star by that of the ref star given the star ids (e.g. target=a,ref=b) and show lightcurve",usage='use "%(prog)s --help" for more information', formatter_class=argparse.RawTextHelpFormatter)

parser.add_argument('--target', help='target star id', type=str, choices=('a','b','c'))
parser.add_argument('--ref', help='reference star id', type=str, choices=('a','b','c'))
parser.add_argument('--band', help='choose band', type=str, default='all', choices=('g','r','z', 'all'))
parser.add_argument('--star', help='choose star', type=int, default=None, choices=(0,1,2))
parser.add_argument('--normed', help='normalize lightcurve?', type=bool, default=False, choices=(True, False))
parser.add_argument('--show_raw_lc', help='show raw lightcurve?', type=bool, default=False, choices=(True, False))
parser.add_argument('--clip', help='clip datapoints (leading,trailing)', type=str, default=None)
parser.add_argument('--clip_sigma', help='keep only the ones that are within +- sigma', type=float, default=None)

args = parser.parse_args()

target = args.target
ref = args.ref
normed = args.normed
band = args.band
star = args.star
show_raw_lc = args.show_raw_lc
clip = args.clip
clip_sigma=args.clip_sigma
if clip is not None:
    clip = [int(i) for i in clip.split(',')]

##load output of `moscatel` in output/*.csv
output_dir = '/home/Jerome/moscatel_output'

try:
    df_g = pd.read_csv(output_dir+'/df_gband.csv', index_col=0, parse_dates=True)
    df_r = pd.read_csv(output_dir+'/df_rband.csv', index_col=0, parse_dates=True)
    df_z = pd.read_csv(output_dir+'/df_zband.csv', index_col=0, parse_dates=True)
    #df.index.to_julian_date()
    #df_grz = pd.concat([df_g, df_r, df_z], axis=1, ignore_index=True)
    df_grz = df_g.join([df_r, df_z])
    if clip is not None:
        df_g = df_g.iloc[clip[0]:-clip[1]]
        df_r = df_r.iloc[clip[0]:-clip[1]]
        df_z = df_z.iloc[clip[0]:-clip[1]]
        df_grz = df_grz.iloc[clip[0]:-clip[1]]
    if clip_sigma is not None:
        df_g = df_g[np.abs(df_g-df_g.mean())<=(clip_sigma*df_g.std())]
        df_r = df_r[np.abs(df_r-df_r.mean())<=(clip_sigma*df_r.std())]
        df_z = df_z[np.abs(df_z-df_z.mean())<=(clip_sigma*df_z.std())]
        df_grz = df_grz[np.abs(df_grz-df_grz.mean())<=(clip_sigma*df_grz.std())]

    filename=output_dir+'/df_grz.csv'
    df_grz.to_csv(filename, mode = 'w', header =df_grz.columns)
except:
    print('ERROR: check missing data in output folder')

print('-----------------------')
print('Showing lightcurve')
print('-----------------------\n')

if band == 'g':
    res = df_phot(target=target, ref=ref, df=df_g, normed=normed, showfig=True)
elif band == 'r':
    res = df_phot(target=target, ref=ref, df=df_r, normed=normed, showfig=True)
elif band == 'z':
    res = df_phot(target=target, ref=ref, df=df_z, normed=normed, showfig=True)
elif band== 'all':
    print('Checking all bands...')
else:
    print('ERROR: check missing data in output folder')

#below are optional
if band=='all':
    if show_raw_lc == True:
        print('-----------------------')
        print('Plotting raw lightcurves of 3 bands')
        print('-----------------------\n')
        res = plot_multicolor(df_grz, star_idx=star)
        #print(res)

    print('-----------------------')
    print('Plotting 3 bands (df_phot)')
    print('-----------------------\n')

    df_grz = df_phot_multicolor(target, ref, df_g, df_r, df_z, star, normed, showfig=True)
    #df_grz.to_csv('grz_band.csv', mode = 'w', header =df_grz.columns)
    #res1, res2, res3 = df_phot_multicolor2(target, ref, df_g, df_r, df_z, star, normed)
    '''print('-----------------------')
    print('Generating scatter matrix')
    print('-----------------------\n')
    plot_matrix(df_z)'''
    #plot specific parameters
    #plot_params(df_z)



print('-----------------------')
print('          DONE')
print('-----------------------\n')
